In [9]:
import pandas as pd
import numpy as np

In [27]:
# loading DataFrame
df = pd.read_csv("train.csv")
df.head()

,physical_part_type,message_timestamp,weekday,shift,status,physical_part_id,s6_sensor0_millimeter_step1,s8_sensor0_millimeter_step1,s8_sensor1_millimeter_step1,s7_sensor0_newton_step1,...,s8_sensor119_millimeter_step1,s0_sensor57_millimeter_step4,s2_sensor23_millimeter_step1,s2_sensor24_millimeter_step1,s8_sensor120_ml_step1,s7_sensor50_mikrometer_step1,s2_sensor25_millimeter_step1,s8_sensor121_binaer_step1,s8_sensor122_millimeter_step1,s3_sensor3_newtonmeter_step1
0,type1,2024-09-01 22:05:44,Sunday,Nachtschicht,OK,gAAAAABnRuZgg4Kol8URwnouW9Hv5RymnFqydE_5oyUU_3...,4606.469076,19.525688,374.198570,8858.706709,...,116.978698,25845.838372,NaN,210.307587,158.979496,35265.817888,217.244319,0.0,727.488871,28.207390
1,type2,2024-09-01 22:07:29,Sunday,Nachtschicht,OK,gAAAAABnRuZfvjtCL7qj_QEGC47fSq-n7brsZXoEV--vJ1...,5886.043819,17.540378,360.603884,8851.987083,...,133.967306,NaN,NaN,204.013170,157.362755,34114.280978,225.185946,0.0,741.645333,25.441928
2,type1,2024-09-01 22:07:55,Sunday,Nachtschicht,OK,gAAAAABnRuZfuXBrn_3FsgN6QXP6DQZPeVgP17o6yPbv4h...,4606.469076,20.445584,371.689206,8856.466834,...,155.401053,25845.838372,NaN,184.667093,NaN,35049.904717,223.404646,0.0,721.249812,25.441928
3,type1,2024-09-01 22:08:38,Sunday,Nachtschicht,OK,gAAAAABnRuZheONxFxB3r6dyfTZt1ehdUXm6a-9Opa35i4...,4606.469076,20.822377,372.461318,8854.226959,...,108.880369,25845.838372,NaN,195.774888,NaN,33682.454636,219.470943,0.0,716.725583,26.253564
4,type1,2024-09-01 22:08:56,Sunday,Nachtschicht,OK,gAAAAABnRuZiqnRUJiO7HqQmkkVmg-m21um0EcSExrMdud...,4606.469076,18.592800,373.371307,8851.987083,...,115.292611,25845.838372,NaN,174.577513,154.129274,34546.107319,240.178550,0.0,775.029771,21.271151

In [31]:
print("Step 0: Loading the dataset...")
cleaned_train_data = pd.read_csv(file_path)
print(f"Initial dataset shape: {cleaned_train_data.shape}")

# Identify columns to modify
columns_to_modify = []

print("Step 4: Identifying uninformative columns to fill with 0s...")
for column in cleaned_train_data.columns:
    # Count unique values in the column
    unique_values = cleaned_train_data[column].nunique()
    
    # If the column has only one unique value, mark it for modification
    if unique_values == 1:
        print(f"Marking column '{column}' as it has only one unique value.")
        columns_to_modify.append(column)
        continue
    
    # Check if the column is a boolean column with mostly zeros
    if cleaned_train_data[column].dtype in [np.int64, np.float64]:
        value_counts = cleaned_train_data[column].value_counts(normalize=True)
        if value_counts.get(0, 0) > 0.6:  # More than 60% zeros
            print(f"Marking column '{column}' as more than 60% of its values are 0.")
            columns_to_modify.append(column)
            continue

    # Check if the column has any missing values and mark it if all values are missing
    if cleaned_train_data[column].isnull().all():
        print(f"Marking column '{column}' as it contains only missing values.")
        columns_to_modify.append(column)

# Fill marked columns with 0
print("Filling marked columns with 0s...")
cleaned_train_data[columns_to_modify] = 0

Step 1: Handling missing values...
Missing values handled.

,physical_part_type,message_timestamp,weekday,shift,status,physical_part_id,s6_sensor0_millimeter_step1,s8_sensor0_millimeter_step1,s8_sensor1_millimeter_step1,s7_sensor0_newton_step1,...,s8_sensor119_millimeter_step1,s0_sensor57_millimeter_step4,s2_sensor23_millimeter_step1,s2_sensor24_millimeter_step1,s8_sensor120_ml_step1,s7_sensor50_mikrometer_step1,s2_sensor25_millimeter_step1,s8_sensor121_binaer_step1,s8_sensor122_millimeter_step1,s3_sensor3_newtonmeter_step1
0,type1,2024-09-01 22:05:44,Sunday,Nachtschicht,OK,gAAAAABnRuZgg4Kol8URwnouW9Hv5RymnFqydE_5oyUU_3...,4606.469076,19.525688,374.198570,8858.706709,...,116.978698,25845.838372,0.556207,210.307587,158.979496,35265.817888,217.244319,0.0,727.488871,28.207390
1,type2,2024-09-01 22:07:29,Sunday,Nachtschicht,OK,gAAAAABnRuZfvjtCL7qj_QEGC47fSq-n7brsZXoEV--vJ1...,5886.043819,17.540378,360.603884,8851.987083,...,133.967306,25845.838372,0.556207,204.013170,157.362755,34114.280978,225.185946,0.0,741.645333,25.441928
2,type1,2024-09-01 22:07:55,Sunday,Nachtschicht,OK,gAAAAABnRuZfuXBrn_3FsgN6QXP6DQZPeVgP17o6yPbv4h...,4606.469076,20.445584,371.689206,8856.466834,...,155.401053,25845.838372,0.556207,184.667093,161.135150,35049.904717,223.404646,0.0,721.249812,25.441928
3,type1,2024-09-01 22:08:38,Sunday,Nachtschicht,OK,gAAAAABnRuZheONxFxB3r6dyfTZt1ehdUXm6a-9Opa35i4...,4606.469076,20.822377,372.461318,8854.226959,...,108.880369,25845.838372,0.556207,195.774888,161.135150,33682.454636,219.470943,0.0,716.725583,26.253564
4,type1,2024-09-01 22:08:56,Sunday,Nachtschicht,OK,gAAAAABnRuZiqnRUJiO7HqQmkkVmg-m21um0EcSExrMdud...,4606.469076,18.592800,373.371307,8851.987083,...,115.292611,25845.838372,0.556207,174.577513,154.129274,34546.107319,240.178550,0.0,775.029771,21.271151

In [51]:
#Hot Encoding types
categorical_columns = ["physical_part_type", "weekday", "shift"]
print(categorical_columns)

df = pd.get_dummies(data=df, columns = categorical_columns)

df.head()

['physical_part_type', 'weekday', 'shift']

,message_timestamp,status,physical_part_id,s6_sensor0_millimeter_step1,s8_sensor0_millimeter_step1,s8_sensor1_millimeter_step1,s7_sensor0_newton_step1,s9_sensor0_kilonewton_step1,s7_sensor1_mikrometer_step1,s0_sensor0_kilonewton_step3,...,physical_part_type_type4,weekday_Friday,weekday_Monday,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday,shift_Fruehschicht,shift_Nachtschicht,shift_Spaetschicht
0,2024-09-01 22:05:44,1,gAAAAABnRuZgg4Kol8URwnouW9Hv5RymnFqydE_5oyUU_3...,4606.469076,19.525688,374.198570,8858.706709,36.836737,28705.766208,-53.537243,...,False,False,False,True,False,False,False,False,True,False
1,2024-09-01 22:07:29,1,gAAAAABnRuZfvjtCL7qj_QEGC47fSq-n7brsZXoEV--vJ1...,5886.043819,17.540378,360.603884,8851.987083,36.836737,27013.209239,-53.537243,...,False,False,False,True,False,False,False,False,True,False
2,2024-09-01 22:07:55,1,gAAAAABnRuZfuXBrn_3FsgN6QXP6DQZPeVgP17o6yPbv4h...,4606.469076,20.445584,371.689206,8856.466834,36.836737,33241.818888,-53.537243,...,False,False,False,True,False,False,False,False,True,False
3,2024-09-01 22:08:38,1,gAAAAABnRuZheONxFxB3r6dyfTZt1ehdUXm6a-9Opa35i4...,4606.469076,20.822377,372.461318,8854.226959,36.836737,32564.796100,-53.537243,...,False,False,False,True,False,False,False,False,True,False
4,2024-09-01 22:08:56,1,gAAAAABnRuZiqnRUJiO7HqQmkkVmg-m21um0EcSExrMdud...,4606.469076,18.592800,373.371307,8851.987083,36.836737,32835.605215,-53.537243,...,False,False,False,True,False,False,False,False,True,False

In [53]:
# replacing OK and NOK with 1 or 0 and dropping timestamp
df.loc[df["status"] == "OK", "status"] = 1
df.loc[df["status"] == "NOK", "status"] = 0
df.head()

,message_timestamp,status,physical_part_id,s6_sensor0_millimeter_step1,s8_sensor0_millimeter_step1,s8_sensor1_millimeter_step1,s7_sensor0_newton_step1,s9_sensor0_kilonewton_step1,s7_sensor1_mikrometer_step1,s0_sensor0_kilonewton_step3,...,physical_part_type_type4,weekday_Friday,weekday_Monday,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday,shift_Fruehschicht,shift_Nachtschicht,shift_Spaetschicht
0,2024-09-01 22:05:44,1,gAAAAABnRuZgg4Kol8URwnouW9Hv5RymnFqydE_5oyUU_3...,4606.469076,19.525688,374.198570,8858.706709,36.836737,28705.766208,-53.537243,...,False,False,False,True,False,False,False,False,True,False
1,2024-09-01 22:07:29,1,gAAAAABnRuZfvjtCL7qj_QEGC47fSq-n7brsZXoEV--vJ1...,5886.043819,17.540378,360.603884,8851.987083,36.836737,27013.209239,-53.537243,...,False,False,False,True,False,False,False,False,True,False
2,2024-09-01 22:07:55,1,gAAAAABnRuZfuXBrn_3FsgN6QXP6DQZPeVgP17o6yPbv4h...,4606.469076,20.445584,371.689206,8856.466834,36.836737,33241.818888,-53.537243,...,False,False,False,True,False,False,False,False,True,False
3,2024-09-01 22:08:38,1,gAAAAABnRuZheONxFxB3r6dyfTZt1ehdUXm6a-9Opa35i4...,4606.469076,20.822377,372.461318,8854.226959,36.836737,32564.796100,-53.537243,...,False,False,False,True,False,False,False,False,True,False
4,2024-09-01 22:08:56,1,gAAAAABnRuZiqnRUJiO7HqQmkkVmg-m21um0EcSExrMdud...,4606.469076,18.592800,373.371307,8851.987083,36.836737,32835.605215,-53.537243,...,False,False,False,True,False,False,False,False,True,False

In [55]:
# Convert 'message_timestamp' to datetime
cleaned_train_data['timestamp'] = pd.to_datetime(cleaned_train_data['message_timestamp'], errors='coerce')

# Convert timestamp to ordinal value (milliseconds since Unix epoch)
cleaned_train_data['ordinal_timestamp'] = df['timestamp'].apply(lambda x: x.value if pd.notna(x) else np.nan)

# Extract hour, minute, second and convert them to their own ordinal features
cleaned_train_data['hour'] = df['timestamp'].dt.hour
cleaned_train_data['minute'] = df['timestamp'].dt.minute
cleaned_train_data['second'] = df['timestamp'].dt.second

# Create columns for each day (each unique day gets its own column)
cleaned_train_data['day'] = df['timestamp'].dt.date
day_columns = pd.get_dummies(df['day'], prefix='day')
cleaned_train_data = pd.concat([df, day_columns], axis=1)

# Drop the original timestamp-related columns
df = df.drop(['message_timestamp', 'timestamp', 'day'], axis=1)

print("Timestamp features added.")

NameError: name 'cleaned_train_data' is not defined